apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
data:
  env: |
    MONGO_DSN=mongodb://root:root@mongodb/nest?authSource=admin
    KAFKA_CLIENT_ID=code-delivery
    KAFKA_BROKER=pkc-lzvrd.us-west4.gcp.confluent.cloud:9092
    KAFKA_CONSUMER_GROUP_ID=code-delivery
    KAFKA_SASL_USERNAME="56E6DPY3IDC53PMH"
    KAFKA_SASL_PASSWORD="h9/CIPb5nuvaDzQj3wF1rT2ggC3PbL5qAoH0ZuY4fgAqXRbXa9+tZ2eARklrnN1x"