version: "3"

services:
  app:
    image: azevedoluis/desafio1-imersao-fsfc2:latest
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - "8000:8001"
